#!/bin/bash -

#########################################################################################
# update
# version:3.2
# update:20180612
#########################################################################################
VER_DIR=/root/eGW/.version
VER_PATH=$1
VER_NAME=$2

function wget_version() {
    [ ! -d $VER_DIR ] && mkdir -p $VER_DIR
    cd $VER_DIR && rm -rf *
    wget $VER_PATH -O $VER_NAME
    (($? == 1)) && exit 10
}

function up_version() {
    tar -zxvf $VER_NAME -C $VER_DIR
    ver=$(find $VER_DIR -maxdepth 1 -type f -name "*.rpm")
    if [ $ver ] && $(file $ver | grep "RPM" &>/dev/null);then
        ver_digest=$(rpm -Kv $ver | awk '/SHA1 digest/{print $5}' | sed 's@(\|)@@g')
        ver_verify=$(cat version.digest)
        if [[ $ver_digest == $ver_verify ]];then
            rpm -qa | grep WCG
            (($? == 0)) && rpm -Uvh $ver --force --allfiles & 
            exit 0
        else
            exit 12
        fi
    else
        exit 11
    fi
}

function ver_update() {
    wget_version
    up_version
}

ver_update
